include:
  # Metadata shared my many jobs
  - local: .gitlab/rules.yml
  - local: .gitlab/artifacts.yml

  # OS builds.
  - local: .gitlab/os-linux.yml
  - local: .gitlab/os-windows.yml

stages:
  - build
  - test
  - analyse

################################################################################
# Job declarations
#
# Each job must pull in each of the following keys:
#
#   - a "base image"
#   - a build script
#   - tags for the jobs
#     - already provided for upload and CI update jobs
#   - rules for when to run the job
#
# Additionally, jobs may also contain:
#
#   - artifacts
#   - dependency/needs jobs for required jobs
################################################################################

# Linux

ubuntu22-debug:build:
  extends:
    - .ubuntu22_debug
    - .cmake_build_linux
    - .linux_builder_tags
    - .cmake_build_artifacts
    - .run_manually
  needs: []

ubuntu22-debug:test:
  extends:
    - .ubuntu22_debug
    - .cmake_test_linux
    - .linux_tester_tags
    - .cmake_test_artifacts
    - .run_automatically
  dependencies:
    - ubuntu22-debug:build
  needs:
    - ubuntu22-debug:build

clang-format-check:analyse:
  extends:
    - .ubuntu22
    - .clang_format_check
    - .linux_tester_tags
    - .run_automatically
  needs: []

clang-tidy-check:analyse:
  extends:
    - .ubuntu22
    - .clang_tidy_check
    - .linux_tester_tags
    - .run_automatically
  dependencies:
    - ubuntu22-debug:build
  needs:
    - ubuntu22-debug:build

ubuntu24-release-pv-latest:build:
  extends:
    - .ubuntu24_pv_latest
    - .cmake_build_linux_with_required_deps
    - .linux_builder_tags
    - .cmake_build_artifacts
    - .run_manually
  needs: []

ubuntu24-release-pv-latest:test:
  extends:
    - .ubuntu24_pv_latest
    - .cmake_test_linux_with_required_deps
    - .linux_tester_tags
    - .cmake_test_artifacts
    - .run_automatically
  dependencies:
    - ubuntu24-release-pv-latest:build
  needs:
    - ubuntu24-release-pv-latest:build

# Windows

windows-vs2022-pv6.0:build:
  extends:
    - .windows_vs2022_pv6.0
    - .cmake_build_windows
    - .windows_builder_tags
    - .cmake_build_artifacts
    - .run_manually
  needs: []

windows-vs2022-pv6.0:test:
  extends:
    - .windows_vs2022_pv6.0
    - .cmake_test_windows
    - .windows_test_tags
    - .cmake_test_artifacts
    - .run_automatically
  dependencies:
    - windows-vs2022-pv6.0:build
  needs:
    - windows-vs2022-pv6.0:build

windows-vs2022-pv6.1:build:
  extends:
    - .windows_vs2022_pv6.1
    - .cmake_build_windows
    - .windows_builder_tags
    - .cmake_build_artifacts
    - .run_manually
  needs: []

windows-vs2022-pv6.1:test:
  extends:
    - .windows_vs2022_pv6.1
    - .cmake_test_windows
    - .windows_test_tags
    - .cmake_test_artifacts
    - .run_automatically
  dependencies:
    - windows-vs2022-pv6.1:build
  needs:
    - windows-vs2022-pv6.1:build
