variables:
  sb_cmake_option_ENABLE_slam:
    value: '-DENABLE_slam=True'
  sb_cmake_option_ENABLE_hesaisdk:
    value: '-DENABLE_hesaisdk=True'
include:
  - project: 'LidarView/lidarview-core'
    file: 'CI/.gitlab-ci-for-lidarview.yml'
    ref: master
