# launch lidarview CI, see https://docs.gitlab.com/ee/ci/multi_project_pipelines.html
.run_automatically:
    rules:
        - if: '$CI_MERGE_REQUEST_ID'
        - if: $CI_COMMIT_BRANCH == "master"
        - when: never

stages:
    - test

lidarview:test:
    variables:
        TRIGGER_MODULE_BRANCH: $CI_COMMIT_REF_NAME
        TRIGGER_MODULE_PATH: LVCore
    extends:
        - .run_automatically
    trigger:
        project: lidarview/lidarview
        branch: master
        strategy: depend
